version: '2'
services:
    lvote-app:
        image: lvote
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://lvote-mysql:3306/lvote?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=90 # gives time for the JHipster Registry to boot before the application
        ports:
            - 8080:8080
    lvote-mysql:
        extends:
            file: mysql.yml
            service: lvote-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
